config/routes.rb
Rails.application.routes.draw do
  root to: "admin/analytic_experiments#index"

  namespace :api do
    resources :analytic_experiments, only: [:index]
  end

  namespace :admin do
    resources :analytic_experiments, only: %i[index show]
  end
end

app/models/analytic_experiment.rb
class AnalyticExperiment < ApplicationRecord
  has_many :experiment_options, dependent: :destroy
  has_many :device_experiments, dependent: :destroy
  has_many :involved_devices, through: :device_experiments, source: :device_token
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/device_experiment.rb
class DeviceExperiment < ApplicationRecord
  belongs_to :analytic_experiment
  belongs_to :device_token
end

app/models/device_experiment_option.rb
class DeviceExperimentOption < ApplicationRecord
  belongs_to :experiment_option
  belongs_to :device_token
end

app/models/device_token.rb
class DeviceToken < ApplicationRecord
  has_many :device_experiment_options, dependent: :destroy
  has_many :experiment_options, through: :device_experiment_options, source: :experiment_option
  has_many :device_experiments, dependent: :destroy
  has_many :available_experiments, through: :device_experiments, source: :analytic_experiment
end

app/models/experiment_option.rb
class ExperimentOption < ApplicationRecord
  belongs_to :analytic_experiment
  has_many :device_experiment_options, dependent: :destroy
  has_many :experiment_devices, through: :device_experiment_options, source: :device_token
end

app/controllers/admin/analytic_experiments_controller.rb
class Admin::AnalyticExperimentsController < ApplicationController
  def index
    @analytic_experiments = ExperimentFetcher.fetch_with_options
  end

  def show
    @experiment_options = ExperimentOptionFetcher.fetch_by_experiment_id(params[:id])
  end
end

app/controllers/api/analytic_experiments_controller.rb
class Api::AnalyticExperimentsController < ApplicationController
  def index
    http_token = request.headers["HTTP_DEVICE_TOKEN"]

    if http_token.blank?
      render json: { error: "'Device-Token' header value is empty!" }, status: :bad_request
      return
    end

    experiment_info = ExperimentProcessor.call(http_token)

    render json: experiment_info.map { |info| { key: info.experiment_name, value: info.name } }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/views/admin/analytic_experiments/index.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Analytic Experiments</h1>
      <p class="mt-2 text-sm text-gray-700">A list of all analytic experiments.</p>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Key</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Involved devices count</th>
            <th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-0">
              <span class="sr-only">Actions</span>
            </th>
          </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
          <% @analytic_experiments.each do |experiment| %>
            <tr>
              <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0"><%= experiment.key %></td>
              <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= experiment.device_count_in_experiment %></td>
              <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-0">
                <%= link_to("Show details", admin_analytic_experiment_path(experiment.id), class: "text-indigo-600 hover:text-indigo-900") %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/analytic_experiments/show.html.erb
<div class="px-4 sm:px-6 lg:px-8">
  <div class="sm:flex sm:items-center">
    <div class="sm:flex-auto">
      <h1 class="text-base font-semibold leading-6 text-gray-900">Analytic experiment variants</h1>
      <p class="mt-2 text-sm text-gray-700">
        A list of variants for <b><%= @experiment_options.first.experiment_name %></b> analytic experiment.
      </p>
    </div>
    <div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none">
      <%= button_to("<< Back",admin_analytic_experiments_path, method: :get, class: "block rounded-md bg-indigo-600 px-3 py-2 text-center text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600") %>
    </div>
  </div>
  <div class="mt-8 flow-root">
    <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
        <table class="min-w-full divide-y divide-gray-300">
          <thead>
          <tr>
            <th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0">Name</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Device Count in Variant</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Device Count in Experiment</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Limit Percentage</th>
            <th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Current Percentage</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200 bg-white">
          <% @experiment_options.each do |option| %>
            <tr>
              <td class="whitespace-nowrap py-5 pl-4 pr-3 text-sm sm:pl-0">
                <span class="font-medium text-gray-900"><%= option.name %></span>
              </td>
              <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                <%= option.device_count_in_option %>
              </td>
              <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                <%= option.device_count_in_experiment %>
              </td>
              <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                <%= option.limit_percentage %>
              </td>
              <td class="whitespace-nowrap px-3 py-5 text-sm text-gray-500">
                <%= option.filling_percentage %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="mt-8">
      <%= yield %>
    </main>
  </body>
</html>